### ISSUE TITLE
where to update the git repo link

### ISSUE THREAD

**Issue by Nath2018** [rtcTo/rtc2gitcli#57]
HI I am new to git&bitbucket & tasked to migrate to RTC project to bitbucket. I have set the target directory & SCMCLI(RTC6.0.4) & the eclipse maven project successfully( i can list migrate-to-git in SCM help) but not sure where to update the git repository (link/users) details? can anybody assist please.

**Comment by WtfJoke** [comment]
Hi @Nath2018 

rtc2git & rtc2gitcli both migrates the RTC project to a local git repository.
If migration is finished you can distribute the git repository to a remote server like bitbucket/github.

[Import an existing Git project into Bitbucket Server](https://confluence.atlassian.com/bitbucketserver/importing-code-from-an-existing-project-776640909.html#Importingcodefromanexistingproject-ImportanexistingGitprojectintoBitbucketServer) shows how to do that with the example of bitbucket. Note that Step 1 is not needed, since you have the repository already cloned locally

Hope that helps
