### ISSUE TITLE
Project Working

### ISSUE THREAD

**Issue by PrajwalSridhar** [rtcTo/rtc2gitcli#77]
Based on this project is it still working and will the long term support provided with regular updates. Also is there any alternative for the same functionality ? RTC to Git

**Comment by reinhapa** [comment]
> Based on this project is it still working and will the long term support provided with regular updates. Also is there any alternative for the same functionality ? RTC to Git

@karthikcad01 there is actually no long term support, as we created this project for others to carry on when we migrated away from RTC back around 2016 though. I do not know of other projects that support an migration but there is always the possibility for such a project.

**Comment by WtfJoke** [comment]
From https://github.com/rtcTo/rtc2git#development-status
> For migrating bigger repositories (> 10000 changes) I advise you to use our other tool [rtc2gitcli](https://github.com/rtcTo/rtc2gitcli) as the IBM Java API is more stable than IBM CLI API. However, this project is easier to run and adapt to different environments.
This project is no longer in active development, because the author has no access to any RTC Server anymore (since they are migrated to git) and changes to code can only be hardly tested.

The last part also applies for this project. This part of the readme was written over 4 years ago and since then we didnt change anything codewise.

**Comment by verhasi** [comment]
@karthikcad01 I was involved in a migration project and failed to use this tool and finally created another one based on the web UI of Jazz. You can find it at https://bitbucket.org/verhasi/migration-new-generation/src/master/ and a short introduction at https://bitbucket.org/blog/migrating-from-ibm-rtc-jazz-to-bitbucket-git.
